services:
  mysql:
    image: mysql:8.0
    container_name: goit-rdb-hw-02-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goit_rdb_hw_02
    volumes:
      - mysql_data:/var/lib/mysql
      - ./p5_create_tables.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
